(() => {
  const d=window.ACTOR_PRODUCTION_DATA, $=s=>document.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pathLink=(p,label)=>p?`<a href="../../${encodeURI(p)}" target="_blank" rel="noopener">${esc(label)}</a>`:'—';
  const display=a=>a.planned?.displayName||a.id;
  const requirementLabel=key=>({baseIdle:'Base Idle',idleVariant:'Idle Variant',tier1:'Attack A (Tier 1)',tier2:'Attack B (Tier 2)',tier3:'Attack C (Tier 3)',hitHold:'Hit Hold',hitRecovery:'Hit Recovery',death:'Death'}[key]||key);
  const poolStatus=s=>({'ready':'연결','pool missing':'풀 없음','pool empty':'빈 풀','lower motion missing':'하위 모션 누락','new motion missing':'새 모션 누락'}[s]||s);
  let storage=null, stored={};
  try{storage=window.localStorage;stored=JSON.parse(storage.getItem('actor-production-v2')||'{}')||{};}catch{storage=null;stored={};}
  let view=stored.view||'recommend', selectedStage=null;
  if(!d){document.body.innerHTML='<main><p>먼저 스캔을 실행하세요: <code>Open Actor Production Tracker.command</code></p></main>';return;}
  $('#revision').textContent=d.scanRevision;
  const persist=()=>{if(!storage)return;try{storage.setItem('actor-production-v2',JSON.stringify({view,filters:Object.fromEntries([...document.querySelectorAll('.controls input,.controls select')].map(e=>[e.id,e.value]))}));}catch{storage=null;}};
  const fill=(id,values)=>[...new Set(values)].sort().forEach(v=>$(id).insertAdjacentHTML('beforeend',`<option value="${esc(v)}">${esc(v)}</option>`));
  fill('#world',d.actors.map(a=>a.world));fill('#type',d.actors.map(a=>a.type));fill('#life',d.actors.map(a=>a.lifecycle));fill('#profile',d.actors.map(a=>a.profile));fill('#import',d.actors.map(a=>a.importProfile));
  Object.entries(stored.filters||{}).forEach(([id,value])=>{if($("#"+id)) $("#"+id).value=value;});
  const metric=(p,label)=>`<div class="track"><span>${label}</span><b>${p.percent===null?'N/A':`${p.percent}%`}</b><i><em style="width:${p.percent||0}%"></em></i><small>${p.percent===null?'해당 없음':`${p.done}/${p.total}`}</small></div>`;
  const percentText=p=>p===null?'N/A':`${p}%`;
  const sourceLinks=a=>{const p=a.sources, packageDoc=a.package?.index||a.package?.brief||a.package?.perfectPixel||a.package?.measurements||a.package?.motionDocs?.[0];return `<div class="links">${pathLink(packageDoc,'패키지 문서')} ${pathLink(a.planned?.sourcePath,'기획 원문')} ${pathLink(a.thumbnailPath,'대표 이미지')} ${pathLink(p.motionProfilePaths[0],'MotionProfile')} ${pathLink(p.definitionPaths[0],'CharacterDefinition')} <button class="copy" data-copy="${esc([packageDoc,a.thumbnailPath,p.motionProfilePaths[0],p.definitionPaths[0],a.planned?.sourcePath].filter(Boolean).join('\n'))}">경로 복사</button></div>`;};
  const identity=a=>a.thumbnailPath?`<img class="thumb ${a.thumbnailKind==='master'?'master':''}" src="../../${encodeURI(a.thumbnailPath)}" alt="${esc(display(a))} 대표 이미지">`:`<div class="placeholder" aria-label="이미지 없음">${esc(display(a).slice(0,1))}<small>${esc(a.lifecycle)}</small></div>`;
  const attackPoolLine=a=>a.attackPoolAudit?`<p class="gapline">공격 풀: A ${esc(poolStatus(a.attackPoolAudit.tiers.tier1.status))} · B ${esc(poolStatus(a.attackPoolAudit.tiers.tier2.status))} · C ${esc(poolStatus(a.attackPoolAudit.tiers.tier3.status))}</p>`:'';
  const enemyAuditLine=a=>a.enemyRuntimeAudit?`<p class="gapline">몬스터: Idle ${a.enemyRuntimeAudit.baseIdle.frameCount}f · Hit ${a.enemyRuntimeAudit.hit.frameCount}f/${a.enemyRuntimeAudit.hitReaction.recoveryVisuallyDistinct?'복귀 구분':a.enemyRuntimeAudit.hitReaction.repeatedRecoveryAllowed?'복귀 반복(승인)':'복귀 중복'} · Defeat ${a.enemyRuntimeAudit.defeatMode==='animated'?`${a.enemyRuntimeAudit.defeat.frameCount}f`:'Fade-only'}</p>`:'';
  const compactCard=a=>`<article class="actor-card"><div class="identity">${identity(a)}<div><span class="stage">${esc(a.stage)}</span><h3>${esc(display(a))}</h3><p>${esc(a.id)} · ${esc(a.world)} · ${esc(a.type)}</p></div></div>${metric(a.progress.package,'설정/패키지')}${metric(a.progress.resources,'리소스')}${metric(a.progress.game,'게임 연결')}<p class="gapline">${a.requirements.missingRequired.length?`필수 공백: ${esc(a.requirements.missingRequired.map(requirementLabel).join(', '))}`:'필수 애니메이션 충족'}</p>${attackPoolLine(a)}${enemyAuditLine(a)}${sourceLinks(a)}</article>`;
  function renderRecommendation(){const rec=d.recommendations.map(r=>{const a=d.actors.find(x=>x.id===r.id);return `<article class="recommend-card">${identity(a)}<div><p class="rank">추천 ${d.recommendations.indexOf(r)+1}</p><h2>${esc(display(a))}</h2><p>${esc(a.world)} · ${esc(a.type)}</p><p class="why">${esc(r.reasons[0]||'현재 제작 흐름 검토')}</p><p><strong>즉시 조치:</strong> ${esc(r.immediateAction)}<br><strong>후속 공백:</strong> ${esc(r.followUp)}</p>${metric(a.progress.package,'설정/패키지')}${metric(a.progress.resources,'리소스')}${metric(a.progress.game,'게임 연결')}${sourceLinks(a)}</div></article>`;}).join(''); $('#recommendation').innerHTML=`<div class="section-heading"><p class="eyebrow">TODAY’S BENCH</p><h2>지금 진행하기 좋은 작업</h2><p>Active만 대상으로, 애니메이션 공백과 이어서 끝낼 수 있는 패키지 자료를 함께 계산했습니다.</p></div><div class="recommend-grid">${rec}</div>`;}
  function renderSummary(){const s=d.summary; $('#summary').innerHTML=[['Active',s.active],['애니메이션 준비',`${s.animationRequirementsReady}/${s.active}`],['공격 풀 연결',`${s.attackPoolsConnected}/${s.activePlayers}`],['몬스터 모션',`${s.enemyMotionQualityReady}/${s.activeEnemies}`],['게임 연결',`${s.runtimeConnected}/${s.active}`]].map(x=>`<article><b>${x[1]}</b><span>${x[0]}</span></article>`).join('');}
  function renderStages(){const labels={Candidate:'후보',Brief:'Brief',Master:'Master',Animation:'Animation',Unity:'Unity',Ready:'Ready',Hold:'보류',Test:'테스트'}; $('#stageOverview').innerHTML=`<div class="section-heading"><h2>제작 단계</h2><p>새 패키지 규칙을 기준으로 한 다음 제작 단계입니다. 기존 자산 관찰값은 카드 안에서 별도로 확인합니다.</p></div><div class="stage-grid">${Object.entries(d.stageCounts).map(([k,n])=>`<button data-stage="${k}"><b>${n}</b><span>${labels[k]}</span></button>`).join('')}</div>`;}
  function filtered(){const val=id=>$(`#${id}`).value, q=val('search').toLowerCase();return d.actors.filter(a=>{const work=val('gap'), anim=a.requirements.missingRequired.length>0, production=['Active','Hold'].includes(a.lifecycle);const workMatch=!work||(production&&work==='package'&&!a.packageComplete)||(production&&work==='animation'&&anim)||(production&&work==='attackpool'&&a.attackPoolAudit&&!a.attackPoolAudit.connected)||(production&&work==='enemymotion'&&a.enemyRuntimeAudit&&!a.enemyRuntimeAudit.motionQualityReady)||(production&&work==='runtime'&&!a.runtimeConnected)||(production&&work==='table'&&a.runtimeChecklist.table===false);return(!q||JSON.stringify(a).toLowerCase().includes(q))&&(!val('world')||a.world===val('world'))&&(!val('type')||a.type===val('type'))&&(!val('life')||a.lifecycle===val('life'))&&(!val('profile')||a.profile===val('profile'))&&(!val('import')||a.importProfile===val('import'))&&workMatch;});}
  function audit(a){const p=a.progress, checklist=p.package.checklist;return `<details class="audit"><summary><span>${esc(display(a))} <small>${esc(a.id)} · ${esc(a.stage)}</small></span><span>${percentText(p.package.percent)} / ${percentText(p.resources.percent)} / ${percentText(p.game.percent)}</span></summary><div>${compactCard(a)}<p><strong>상세 감사</strong><br>패키지: index ${checklist.index?'✓':'—'} · brief ${checklist.brief?'✓':'—'} · PerfectPixel ${checklist.perfectPixelInput?'✓':'—'} · measurements ${checklist.measurements?'✓':'—'} · motion ${checklist.motionBrief?'✓':'—'} · master ${checklist.master?'✓':'—'}<br>런타임: MotionProfile ${p.game.checklist.motionProfile?'✓':'—'} · Profile 재생 ${p.game.checklist.profilePlayable===null?'N/A':p.game.checklist.profilePlayable?'✓':'—'} · CharacterDefinition ${p.game.checklist.characterDefinition===null?'N/A':p.game.checklist.characterDefinition?'✓':'—'} · 공격 풀 ${p.game.checklist.attackPools===null?'N/A':p.game.checklist.attackPools?'✓':'—'} · 테이블 ${p.game.checklist.table===null?'N/A':p.game.checklist.table?'✓':'—'}<br>${a.warnings.map(esc).join('<br>')}</p></div></details>`;}
  function showList(list,title){$('#actors').innerHTML=list.length?`<div class="list-heading"><h2>${title}</h2><p>${list.length}명 · 카드를 열면 상세 감사와 원본 경로를 봅니다.</p></div>${list.map(audit).join('')}`:'<p class="empty">표시할 배우가 없습니다.</p>';$('#count').textContent=`${list.length}명 표시`;}
  function showStageBoard(){const order=['Brief','Master','Animation','Unity','Ready'];const groups=order.map(stage=>{const list=d.actors.filter(a=>a.stage===stage);return `<section class="stage-lane"><h2>${stage} <small>${list.length}</small></h2>${list.length?list.map(audit).join(''):'<p>현재 없음</p>'}</section>`;}).join('');$('#actors').innerHTML=`<div class="list-heading"><h2>단계별 작업 보드</h2><p>패키지 규칙을 먼저 적용한 현재 단계입니다.</p></div><div class="stage-board">${groups}</div>`;$('#count').textContent=`Active ${d.summary.active}명`;}
  function render(){document.querySelectorAll('.views button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view))); const rec=view==='recommend', all=view==='all';$('#recommendation').hidden=!rec;$('#summary').hidden=!(rec||view==='stages');$('#stageOverview').hidden=!(rec||view==='stages');$('#filters').hidden=!all; if(rec){$('#actors').innerHTML='';$('#count').textContent='';} else if(view==='stages') showStageBoard(); else if(view==='candidates') showList(d.actors.filter(a=>a.lifecycle==='Candidate'),'후보 뱅크'); else if(view==='parked') showList(d.actors.filter(a=>['Hold','Test'].includes(a.lifecycle)),'보류·테스트'); else showList(selectedStage?d.actors.filter(a=>a.stage===selectedStage):filtered(),selectedStage?`${selectedStage} 단계 목록`:'전체 목록');persist();}
  document.querySelectorAll('.views button').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;selectedStage=null;render();}));document.querySelectorAll('.controls input,.controls select').forEach(e=>e.addEventListener('input',()=>{selectedStage=null;render();}));$('#reset').addEventListener('click',()=>{document.querySelectorAll('.controls input,.controls select').forEach(e=>e.value='');selectedStage=null;render();});document.addEventListener('click',e=>{const stage=e.target.closest('[data-stage]');if(stage){selectedStage=stage.dataset.stage;view='all';render();return;}const b=e.target.closest('.copy');if(!b)return;const done=()=>{b.textContent='복사됨';setTimeout(()=>b.textContent='경로 복사',1200);};if(navigator.clipboard)navigator.clipboard.writeText(b.dataset.copy).then(done).catch(()=>window.prompt('경로를 복사하세요',b.dataset.copy));else window.prompt('경로를 복사하세요',b.dataset.copy);});renderRecommendation();renderSummary();renderStages();render();
})();
